#
# .travis.yml
# =============================================================================
# Reporter Multilang. Version 0.1
# =============================================================================
# A tool to generate human-readable reports based on data from various sources
# with the focus on its implementation using a series of programming languages.
#
# This is the configuration of the project characteristics
# used by the Travis CI (continuous integration) service
# to rebuild the project on every push and pull request.
#

%YAML 1.1
---

language: node_js

node_js:
    - "7"
    - "6"

sudo: required

dist: trusty

before_install:
    - sudo apt-get update

script:
    ## TODO: Building all the packages under reporter-cli.
    - cd reporter-cli && ls -al

    ## TODO: Building all the packages under sql-pdf.
    - cd sql-pdf && ls -al

    ## Building the SQL to PDF reporter package as the Perl 5 (5.10+) impl.
    - cd perl && ls -al
              && make clean
              && make clean
              && ls -al
              && make all
              && make all
              && ls -al
              && ls -al bin lib src
              && ls -al
              && echo

    ## Returning to the previous working dir.
    - cd - && ls -al

    ## Building the SQL to PDF reporter package as the Python 3 impl.
    - cd python && ls -al
                && make clean
                && make clean
                && ls -al
                && make all
                && make all
                && ls -al
                && ls -al bin lib src
                && ls -al
                && echo

    ## Returning to the previous working dir.
    - cd - && ls -al

    ## Building the SQL to PDF reporter package as the Vala impl.
    - cd vala && ls -al
              && make clean
              && make clean
              && ls -al
              && make all
              && make all
              && ls -al
              && ls -al bin lib src
              && ls -al
              && echo

    ## Returning to the previous working dir.
    - cd - && ls -al

    ## Building the SQL to PDF reporter package as the Genie impl.
    - cd genie && ls -al
               && make clean
               && make clean
               && ls -al
               && make all
               && make all
               && ls -al
               && ls -al bin lib src
               && ls -al
               && echo

    ## Returning to the previous working dir.
    - cd - && ls -al

    ## Building the SQL to PDF reporter package as the Go impl.
    - cd go && ls -al
            && make clean
            && make clean
            && ls -al
            && make all
            && make all
            && ls -al 
            && ls -al bin lib obj src
            && ls -al
            && echo

    ## Returning to the previous working dir.
    - cd - && ls -al

    ##
    # Building the SQL to PDF reporter package
    # as the JavaScript (ES5/Node.js) impl.
    #
    - cd js && ls -al
            && make clean
            && make clean
            && ls -al
            && make all
            && make all
            && ls -al
            && ls -al bin lib src
            && ls -al
            && echo

    ## Returning to the previous working dir.
    - cd - && ls -al

    ## Going one level up.
    - cd .. && ls -al

    ## TODO: Building all the packages under sql-csv.
    - cd sql-csv && ls -al

    ## Returning to the previous working dir.
    - cd - && ls -al

    ## Going one level up.
    - cd .. && ls -al

...

# vim:set nu:et:ts=4:sw=4:
